var shuffleSequence = seq("intro", sepWith("sep",  seq("practice")), "practiceover", sepWith("sep", rshuffle(startsWith("first-item"), startsWith("firstfiller"))));

var continueMessage = ["Klikni zde"];

var aj = "AcceptabilityJudgment";

var q = "Question";

var completionMessage = "[Zadané odpovědi jsou odeslány na server. Děkujeme za spolupráci!]";

var ms = "Message";

var defaults = [    
    "Separator", { transfer: 800,
                   normalMessage: "Počkejte prosím na další položku v experimentu.",
                   errorMessage: "Špatně. Počkejte prosím na další položku v experimentu." 
		 },
    "AcceptabilityJudgment", { as: ["1", "2", "3", "4", "5", "6", "7"],
                               presentAsScale: true,
                               leftComment: "(absolutně nepřijatelná věta)", rightComment: "(věta je naprosto v pořádku)" },
    "Message", { hideProgressBar: true, transfer: "click" }
];

 var progressBarText = "";

var items = [ ["sep", "Separator", { }],
 
	      ["intro", "Form", {continueMessage: "Pro vstup do experimentu, klikněte zde", html: { include: "example_intro.html" }}],

	      ["practice", aj, {s: {html: "<p>Pět kamarádů vyrazilo do lesa na houby. Rozhodněte jak moc, na škále od 1 do 7, věta zapsaná jedním z nich významově odpovídá tomu, co popisuje tabulka.</p><center><table><tr><th>Jméno</th><th>Houba</th></tr><tr><td>Petr</td><td>hřib</td></tr><tr><td>Marie</td><td>bedla</td></tr><tr><td>Jan</td><td>muchomůrka</td></tr><tr><td>Markéta</td><td>liška</td></tr><tr><td>Jana</td><td>kozák</td></tr></table><p>Věta: <b>Každý z kamarádů našel po jedné houbě.  </b></p><p><i>Tato věta je v daném kontextu pořádku. Pokud souhlasíte, vyberte jednu z možností v pravém konci škály (nejspíš 7).</i></p></center>"}}],
    ["practice", aj, {s: {html: "<p>Pět vlků vyrazilo na lov a ulovila zvířata, viz tabulka. Rozhodněte jak moc, na škále od 1 do 7, věta zapsaná myslivcem významově odpovídá tomu, co popisuje tabulka.</p><center><table><tr><th>Vlk</th><th>Zvíře</th></tr><tr><td>vlk1</td><td>zajíc</td></tr><tr><td>vlk2</td><td>srnec</td></tr><tr><td>vlk3</td><td>jelen</td></tr><tr><td>vlk4</td><td>liška</td></tr><tr><td>vlk5</td><td>prase</td></tr></table><p>Věta: <b>Skupina vlků ulovila jednoho zajíce.  </b></p><p><i>Tato věta je gramaticky v pořádku, ale neodpovídá kontextu, který je reprezentován tabulkou. Pokud souhlasíte, vyberte jednu z možností v levém konci škály (nejspíš 1).</i></p></center></i></p>"}}],
    ["practice", aj, {s: {html: "<p>Pět spisovatelů psalo knihy, viz tabulka. Rozhodněte jak moc, na škále od 1 do 7, věta zapsaná jedním z nich významově odpovídá tomu, co popisuje tabulka.</p><center><table><tr><th>Jméno</th><th>Kniha</th></tr><tr><td>Petr</td><td>román</td></tr><tr><td>Marie</td><td>kniha povídek</td></tr><tr><td>Jan</td><td>sbírka básní</td></tr><tr><td>Markéta</td><td>detektivka</td></tr><tr><td>Jana</td><td>fantasy kniha</td></tr></table><p>Věta: <b>Každý z pěti spisovatelů napsal jednu knihu.  </b></p><p><i>Tato věta je v daném kontextu pořádku. Pokud souhlasíte, vyberte jednu z možností v pravém konci škály (nejspíš 7).</i></p></center>"}}],

	      ["practiceover", "Message", {continueMessage: "Klikněte zde pro pokračování experimentu", html: ["div", ["p", "Zde končí přípravná část experimentu. Klikněte níže pro vstup do experimentu."]]}],

[["first-item1-perf", 1], aj, {s: {html: "<p>Petr rád chodí na ryby. Během minulého týdne si výsledky své oblíbené aktivity zaznamenával do seznamu. Rozhodněte jak moc, na škále od 1 do 7, věta přiložená k seznamu významově odpovídá tomu, co Petr do seznamu zaznamenal. </p><center> <p> <table><tr><th>Den</th><th>Ryba</th></tr><tr><td>Pondělí</td><td>Amur</td></tr><tr><td>Úterý</td><td>Pstruh</td></tr><tr><td>Středa</td><td>Štika</td></tr><tr><td>Čtvrtek</td><td>Amur</td></tr><tr><td>Pátek</td><td>Candát</td></tr><tr><td>Sobota</td><td>Okoun</td></tr><tr><td>Neděle</td><td>Cejn</td></tr></table> </p><p>Věta: <b>Petr každý den chytnul jednu rybu.  </b></center></p>"}}],
[["first-item1-hab", 1], aj, {s: {html: "<p>Petr rád chodí na ryby. Během minulého týdne si výsledky své oblíbené aktivity zaznamenával do seznamu. Rozhodněte jak moc, na škále od 1 do 7, věta přiložená k seznamu významově odpovídá tomu, co Petr do seznamu zaznamenal. </p><center> <p> <table><tr><th>Den</th><th>Ryba</th></tr><tr><td>Pondělí</td><td>Amur</td></tr><tr><td>Úterý</td><td>Pstruh</td></tr><tr><td>Středa</td><td>Štika</td></tr><tr><td>Čtvrtek</td><td>Amur</td></tr><tr><td>Pátek</td><td>Candát</td></tr><tr><td>Sobota</td><td>Okoun</td></tr><tr><td>Neděle</td><td>Cejn</td></tr></table> </p><p>Věta: <b>Petr chytával jednu rybu.   </b></center></p>"}}],
[["first-item1-gen", 1], aj, {s: {html: "<p>Petr rád chodí na ryby. Během minulého týdne si výsledky své oblíbené aktivity zaznamenával do seznamu. Rozhodněte jak moc, na škále od 1 do 7, věta přiložená k seznamu významově odpovídá tomu, co Petr do seznamu zaznamenal. </p><center> <p> <table><tr><th>Den</th><th>Ryba</th></tr><tr><td>Pondělí</td><td>Amur</td></tr><tr><td>Úterý</td><td>Pstruh</td></tr><tr><td>Středa</td><td>Štika</td></tr><tr><td>Čtvrtek</td><td>Amur</td></tr><tr><td>Pátek</td><td>Candát</td></tr><tr><td>Sobota</td><td>Okoun</td></tr><tr><td>Neděle</td><td>Cejn</td></tr></table> </p><p>Věta: <b>Petr po ránu chytával jednu rybu.   </b></center></p>"}}],

[["first-item2-perf", 2], aj, {s: {html: "<p>Oslice Lucie je nepřátelská k ostatním zvířatům a často je po jídle kope. Její ošetřovatelka nakopnutá zvířata zapisuje do seznamu. Rozhodněte jak moc, na škále od 1 do 7, věta přiložená k seznamu významově odpovídá tomu, co ošetřovatelka do seznamu zaznamenala.  </p><center> <p> <table><tr><th>Den</th><th>Zvíře</th></tr><tr><td>Pondělí</td><td>Ovce</td></tr><tr><td>Úterý</td><td>Pštros</td></tr><tr><td>Středa</td><td>Koza</td></tr><tr><td>Čtvrtek</td><td>Slepice</td></tr><tr><td>Pátek</td><td>Lama</td></tr><tr><td>Sobota</td><td>Husa</td></tr><tr><td>Neděle</td><td>Prase</td></tr></table> </p><p>Věta: <b>Lucie každý den kopla jedno zvíře.  </b></center></p>"}}],
[["first-item2-hab", 2], aj, {s: {html: "<p>Oslice Lucie je nepřátelská k ostatním zvířatům a často je po jídle kope. Její ošetřovatelka nakopnutá zvířata zapisuje do seznamu. Rozhodněte jak moc, na škále od 1 do 7, věta přiložená k seznamu významově odpovídá tomu, co ošetřovatelka do seznamu zaznamenala.  </p><center> <p> <table><tr><th>Den</th><th>Zvíře</th></tr><tr><td>Pondělí</td><td>Ovce</td></tr><tr><td>Úterý</td><td>Pštros</td></tr><tr><td>Středa</td><td>Koza</td></tr><tr><td>Čtvrtek</td><td>Slepice</td></tr><tr><td>Pátek</td><td>Lama</td></tr><tr><td>Sobota</td><td>Husa</td></tr><tr><td>Neděle</td><td>Prase</td></tr></table> </p><p>Věta: <b>Lucie kopávala jedno zvíře.  </b></center></p>"}}],
[["first-item2-gen", 2], aj, {s: {html: "<p>Oslice Lucie je nepřátelská k ostatním zvířatům a často je po jídle kope. Její ošetřovatelka nakopnutá zvířata zapisuje do seznamu. Rozhodněte jak moc, na škále od 1 do 7, věta přiložená k seznamu významově odpovídá tomu, co ošetřovatelka do seznamu zaznamenala.  </p><center> <p> <table><tr><th>Den</th><th>Zvíře</th></tr><tr><td>Pondělí</td><td>Ovce</td></tr><tr><td>Úterý</td><td>Pštros</td></tr><tr><td>Středa</td><td>Koza</td></tr><tr><td>Čtvrtek</td><td>Slepice</td></tr><tr><td>Pátek</td><td>Lama</td></tr><tr><td>Sobota</td><td>Husa</td></tr><tr><td>Neděle</td><td>Prase</td></tr></table> </p><p>Věta: <b>Lucie po jídle kopávala jedno zvíře.  </b></center></p>"}}],

[["first-item3-perf", 3], aj, {s: {html: "<p>Pavel je literární teoretik a zvlášť po ránu zapomíná adjektiva hodící se k analýze literárních děl. Jeho kolega Josef si z něj dělá legraci a zapomenutá slova si zaznamenává do seznamu. Rozhodněte jak moc, na škále od 1 do 7, věta přiložená k seznamu významově odpovídá tomu, co Josef do seznamu zaznamenal. </p><center> <p> <table><tr><th>Den</th><th>Adjektivum</th></tr><tr><td>Pondělí</td><td>Melancholický</td></tr><tr><td>Úterý</td><td>Patetický</td></tr><tr><td>Středa</td><td>Fantaskní</td></tr><tr><td>Čtvrtek</td><td>Cynický</td></tr><tr><td>Pátek</td><td>Vycizelovaný</td></tr><tr><td>Sobota</td><td>Mystický</td></tr><tr><td>Neděle</td><td>Existenciální</td></tr></table> </p><p>Věta: <b>Pavel každý den zapomněl jedno slovo. </b></center></p>"}}],
[["first-item3-hab", 3], aj, {s: {html: "<p>Pavel je literární teoretik a zvlášť po ránu zapomíná adjektiva hodící se k analýze literárních děl. Jeho kolega Josef si z něj dělá legraci a zapomenutá slova si zaznamenává do seznamu. Rozhodněte jak moc, na škále od 1 do 7, věta přiložená k seznamu významově odpovídá tomu, co Josef do seznamu zaznamenal. </p><center> <p> <table><tr><th>Den</th><th>Adjektivum</th></tr><tr><td>Pondělí</td><td>Melancholický</td></tr><tr><td>Úterý</td><td>Patetický</td></tr><tr><td>Středa</td><td>Fantaskní</td></tr><tr><td>Čtvrtek</td><td>Cynický</td></tr><tr><td>Pátek</td><td>Vycizelovaný</td></tr><tr><td>Sobota</td><td>Mystický</td></tr><tr><td>Neděle</td><td>Existenciální</td></tr></table> </p><p>Věta: <b>Pavel zapomínával jedno slovo. </b></center></p>"}}],
[["first-item3-gen", 3], aj, {s: {html: "<p>Pavel je literární teoretik a zvlášť po ránu zapomíná adjektiva hodící se k analýze literárních děl. Jeho kolega Josef si z něj dělá legraci a zapomenutá slova si zaznamenává do seznamu. Rozhodněte jak moc, na škále od 1 do 7, věta přiložená k seznamu významově odpovídá tomu, co Josef do seznamu zaznamenal. </p><center> <p> <table><tr><th>Den</th><th>Adjektivum</th></tr><tr><td>Pondělí</td><td>Melancholický</td></tr><tr><td>Úterý</td><td>Patetický</td></tr><tr><td>Středa</td><td>Fantaskní</td></tr><tr><td>Čtvrtek</td><td>Cynický</td></tr><tr><td>Pátek</td><td>Vycizelovaný</td></tr><tr><td>Sobota</td><td>Mystický</td></tr><tr><td>Neděle</td><td>Existenciální</td></tr></table> </p><p>Věta: <b>Pavel po ránu zapomínával jedno slovo. </b></center></p>"}}],

[["first-item4-perf", 4], aj, {s: {html: "<p>Neúspěšná elektrikářka Markéta často seká do kabelů (zvlášť na konci směny), místo toho aby je opravovala. Aby v tom měla přehled, zaznamenává si přeseknuté kabely do seznamu. Rozhodněte jak moc, na škále od 1 do 7, věta přiložená k seznamu významově odpovídá tomu, co Markéta do seznamu zaznamenala.  </p><center> <p> <table><tr><th>Den</th><th>Barva</th></tr><tr><td>Pondělí</td><td>Modrý</td></tr><tr><td>Úterý</td><td>Červený</td></tr><tr><td>Středa</td><td>Žlutý</td></tr><tr><td>Čtvrtek</td><td>Oranžový</td></tr><tr><td>Pátek</td><td>Zelený</td></tr><tr><td>Sobota</td><td>Černý</td></tr><tr><td>Neděle</td><td>Bílý</td></tr></table> </p><p>Věta: <b> Markéta každý den přeseknula jeden kabel. </b></center></p>"}}],
[["first-item4-hab", 4], aj, {s: {html: "<p>Neúspěšná elektrikářka Markéta často seká do kabelů (zvlášť na konci směny), místo toho aby je opravovala. Aby v tom měla přehled, zaznamenává si přeseknuté kabely do seznamu. Rozhodněte jak moc, na škále od 1 do 7, věta přiložená k seznamu významově odpovídá tomu, co Markéta do seznamu zaznamenala.  </p><center> <p> <table><tr><th>Den</th><th>Barva</th></tr><tr><td>Pondělí</td><td>Modrý</td></tr><tr><td>Úterý</td><td>Červený</td></tr><tr><td>Středa</td><td>Žlutý</td></tr><tr><td>Čtvrtek</td><td>Oranžový</td></tr><tr><td>Pátek</td><td>Zelený</td></tr><tr><td>Sobota</td><td>Černý</td></tr><tr><td>Neděle</td><td>Bílý</td></tr></table> </p><p>Věta: <b> Markéta sekávala jeden kabel. </b></center></p>"}}],
[["first-item4-gen", 4], aj, {s: {html: "<p>Neúspěšná elektrikářka Markéta často seká do kabelů (zvlášť na konci směny), místo toho aby je opravovala. Aby v tom měla přehled, zaznamenává si přeseknuté kabely do seznamu. Rozhodněte jak moc, na škále od 1 do 7, věta přiložená k seznamu významově odpovídá tomu, co Markéta do seznamu zaznamenala.  </p><center> <p> <table><tr><th>Den</th><th>Barva</th></tr><tr><td>Pondělí</td><td>Modrý</td></tr><tr><td>Úterý</td><td>Červený</td></tr><tr><td>Středa</td><td>Žlutý</td></tr><tr><td>Čtvrtek</td><td>Oranžový</td></tr><tr><td>Pátek</td><td>Zelený</td></tr><tr><td>Sobota</td><td>Černý</td></tr><tr><td>Neděle</td><td>Bílý</td></tr></table> </p><p>Věta: <b> Markéta na konci směny sekávala jeden kabel. </b></center></p>"}}],

[["first-item5-perf", 5], aj, {s: {html: "<p>Jonáš je kocour, který se nerad mazlí, ale zato hodně často (nejčastěji před snídaní) kouše členy své domácnosti. Jeho majitelka Anna si jednotlivá kousnutí zaznamená do seznamu. Rozhodněte jak moc, na škále od 1 do 7, věta přiložená k seznamu významově odpovídá tomu, co Anna do seznamu zaznamenala.  </p><center> <p> <table><tr><th>Den</th><th>Jméno</th></tr><tr><td>Pondělí</td><td>Šimon</td></tr><tr><td>Úterý</td><td>Michael</td></tr><tr><td>Středa</td><td>Matouš</td></tr><tr><td>Čtvrtek</td><td>Anna</td></tr><tr><td>Pátek</td><td>Lída</td></tr><tr><td>Sobota</td><td>Iva</td></tr><tr><td>Neděle</td><td>Kamil</td></tr></table> </p><p>Věta: <b> Jonáš každý den kousl jednu osobu. </b></center></p>"}}],
[["first-item5-hab", 5], aj, {s: {html: "<p>Jonáš je kocour, který se nerad mazlí, ale zato hodně často (nejčastěji před snídaní) kouše členy své domácnosti. Jeho majitelka Anna si jednotlivá kousnutí zaznamená do seznamu. Rozhodněte jak moc, na škále od 1 do 7, věta přiložená k seznamu významově odpovídá tomu, co Anna do seznamu zaznamenala.  </p><center> <p> <table><tr><th>Den</th><th>Jméno</th></tr><tr><td>Pondělí</td><td>Šimon</td></tr><tr><td>Úterý</td><td>Michael</td></tr><tr><td>Středa</td><td>Matouš</td></tr><tr><td>Čtvrtek</td><td>Anna</td></tr><tr><td>Pátek</td><td>Lída</td></tr><tr><td>Sobota</td><td>Iva</td></tr><tr><td>Neděle</td><td>Kamil</td></tr></table> </p><p>Věta: <b> Jonáš kousával jednu osobu. </b></center></p>"}}],
[["first-item5-gen", 5], aj, {s: {html: "<p>Jonáš je kocour, který se nerad mazlí, ale zato hodně často (nejčastěji před snídaní) kouše členy své domácnosti. Jeho majitelka Anna si jednotlivá kousnutí zaznamená do seznamu. Rozhodněte jak moc, na škále od 1 do 7, věta přiložená k seznamu významově odpovídá tomu, co Anna do seznamu zaznamenala.  </p><center> <p> <table><tr><th>Den</th><th>Jméno</th></tr><tr><td>Pondělí</td><td>Šimon</td></tr><tr><td>Úterý</td><td>Michael</td></tr><tr><td>Středa</td><td>Matouš</td></tr><tr><td>Čtvrtek</td><td>Anna</td></tr><tr><td>Pátek</td><td>Lída</td></tr><tr><td>Sobota</td><td>Iva</td></tr><tr><td>Neděle</td><td>Kamil</td></tr></table> </p><p>Věta: <b> Jonáš před snídaní kousával jednu osobu. </b></center></p>"}}],

[["first-item6-perf", 6], aj, {s: {html: "<p>Důchodkyně Irena našla novou zálibu v pěstování stromů. Stromy, které zasadila (nejčastěji večer), si zaznamenává do seznamu. Rozhodněte jak moc, na škále od 1 do 7, věta přiložená k seznamu významově odpovídá tomu, co Irena do seznamu zaznamenala. </p><center> <p> <table><tr><th>Den</th><th>Strom</th></tr><tr><td>Pondělí</td><td>Jabloň</td></tr><tr><td>Úterý</td><td>Buk</td></tr><tr><td>Středa</td><td>Hrušeň</td></tr><tr><td>Čtvrtek</td><td>Javor</td></tr><tr><td>Pátek</td><td>Třešeň</td></tr><tr><td>Sobota</td><td>Dub</td></tr><tr><td>Neděle</td><td>Slivoň</td></tr></table> </p><p>Věta: <b> Irena každý den zasadila jeden strom. </b></center></p>"}}],
[["first-item6-hab", 6], aj, {s: {html: "<p>Důchodkyně Irena našla novou zálibu v pěstování stromů. Stromy, které zasadila (nejčastěji večer), si zaznamenává do seznamu. Rozhodněte jak moc, na škále od 1 do 7, věta přiložená k seznamu významově odpovídá tomu, co Irena do seznamu zaznamenala. </p><center> <p> <table><tr><th>Den</th><th>Strom</th></tr><tr><td>Pondělí</td><td>Jabloň</td></tr><tr><td>Úterý</td><td>Buk</td></tr><tr><td>Středa</td><td>Hrušeň</td></tr><tr><td>Čtvrtek</td><td>Javor</td></tr><tr><td>Pátek</td><td>Třešeň</td></tr><tr><td>Sobota</td><td>Dub</td></tr><tr><td>Neděle</td><td>Slivoň</td></tr></table> </p><p>Věta: <b> Irena sázívala jeden strom. </b></center></p>"}}],
[["first-item6-gen", 6], aj, {s: {html: "<p>Důchodkyně Irena našla novou zálibu v pěstování stromů. Stromy, které zasadila (nejčastěji večer), si zaznamenává do seznamu. Rozhodněte jak moc, na škále od 1 do 7, věta přiložená k seznamu významově odpovídá tomu, co Irena do seznamu zaznamenala. </p><center> <p> <table><tr><th>Den</th><th>Strom</th></tr><tr><td>Pondělí</td><td>Jabloň</td></tr><tr><td>Úterý</td><td>Buk</td></tr><tr><td>Středa</td><td>Hrušeň</td></tr><tr><td>Čtvrtek</td><td>Javor</td></tr><tr><td>Pátek</td><td>Třešeň</td></tr><tr><td>Sobota</td><td>Dub</td></tr><tr><td>Neděle</td><td>Slivoň</td></tr></table> </p><p>Věta: <b> Irena sázívala k večeru jeden strom. </b></center></p>"}}],

[["first-item7-perf", 7], aj, {s: {html: "<p>Básník Kryštof si během týdne zapisuje do seznamu, kterou báseň kdy (nejčastěji po večeři) psal. Rozhodněte jak moc, na škále od 1 do 7, věta přiložená k seznamu významově odpovídá tomu, co Kryštof do seznamu zaznamenal. </p><center> <p> <table><tr><th>Den</th><th>Báseň</th></tr><tr><td>Pondělí</td><td>O noci</td></tr><tr><td>Úterý</td><td>O lásce</td></tr><tr><td>Středa</td><td>O přírodě</td></tr><tr><td>Čtvrtek</td><td>O lidech</td></tr><tr><td>Pátek</td><td>O hvězdách</td></tr><tr><td>Sobota</td><td>O vodě</td></tr><tr><td>Neděle</td><td>O včelách</td></tr></table> </p><p>Věta: <b> Kryštof každý den napsal jednu báseň. </b></center></p>"}}],
[["first-item7-hab", 7], aj, {s: {html: "<p>Básník Kryštof si během týdne zapisuje do seznamu, kterou báseň kdy (nejčastěji po večeři) psal. Rozhodněte jak moc, na škále od 1 do 7, věta přiložená k seznamu významově odpovídá tomu, co Kryštof do seznamu zaznamenal. </p><center> <p> <table><tr><th>Den</th><th>Báseň</th></tr><tr><td>Pondělí</td><td>O noci</td></tr><tr><td>Úterý</td><td>O lásce</td></tr><tr><td>Středa</td><td>O přírodě</td></tr><tr><td>Čtvrtek</td><td>O lidech</td></tr><tr><td>Pátek</td><td>O hvězdách</td></tr><tr><td>Sobota</td><td>O vodě</td></tr><tr><td>Neděle</td><td>O včelách</td></tr></table> </p><p>Věta: <b> Kryštof psával jednu báseň. </b></center></p>"}}],
[["first-item7-gen", 7], aj, {s: {html: "<p>Básník Kryštof si během týdne zapisuje do seznamu, kterou báseň kdy (nejčastěji po večeři) psal. Rozhodněte jak moc, na škále od 1 do 7, věta přiložená k seznamu významově odpovídá tomu, co Kryštof do seznamu zaznamenal. </p><center> <p> <table><tr><th>Den</th><th>Báseň</th></tr><tr><td>Pondělí</td><td>O noci</td></tr><tr><td>Úterý</td><td>O lásce</td></tr><tr><td>Středa</td><td>O přírodě</td></tr><tr><td>Čtvrtek</td><td>O lidech</td></tr><tr><td>Pátek</td><td>O hvězdách</td></tr><tr><td>Sobota</td><td>O vodě</td></tr><tr><td>Neděle</td><td>O včelách</td></tr></table> </p><p>Věta: <b> Kryštof psával po večeři jednu báseň. </b></center></p>"}}],

[["first-item8-perf", 8], aj, {s: {html: "<p>Skvělá kuchařka Edita si do seznamu zapisuje, které jídlo (nejčastěji oběd) kdy uvařila, aby se často neopakovala. Rozhodněte jak moc, na škále od 1 do 7, věta přiložená k seznamu významově odpovídá tomu, co Edita do seznamu zaznamenala.  </p><center> <p> <table><tr><th>Den</th><th>Jídlo</th></tr><tr><td>Pondělí</td><td>Guláš</td></tr><tr><td>Úterý</td><td>Lasagne</td></tr><tr><td>Středa</td><td>Koprovka</td></tr><tr><td>Čtvrtek</td><td>Špagety</td></tr><tr><td>Pátek</td><td>Rajská</td></tr><tr><td>Sobota</td><td>Segedýn</td></tr><tr><td>Neděle</td><td>Svíčková</td></tr></table> </p><p>Věta: <b> Edita každý den uvařila jedno jídlo. </b></center></p>"}}],
[["first-item8-hab", 8], aj, {s: {html: "<p>Skvělá kuchařka Edita si do seznamu zapisuje, které jídlo (nejčastěji oběd) kdy uvařila, aby se často neopakovala. Rozhodněte jak moc, na škále od 1 do 7, věta přiložená k seznamu významově odpovídá tomu, co Edita do seznamu zaznamenala.  </p><center> <p> <table><tr><th>Den</th><th>Jídlo</th></tr><tr><td>Pondělí</td><td>Guláš</td></tr><tr><td>Úterý</td><td>Lasagne</td></tr><tr><td>Středa</td><td>Koprovka</td></tr><tr><td>Čtvrtek</td><td>Špagety</td></tr><tr><td>Pátek</td><td>Rajská</td></tr><tr><td>Sobota</td><td>Segedýn</td></tr><tr><td>Neděle</td><td>Svíčková</td></tr></table> </p><p>Věta: <b> Edita vařívala jedno jídlo. </b></center></p>"}}],
[["first-item8-gen", 8], aj, {s: {html: "<p>Skvělá kuchařka Edita si do seznamu zapisuje, které jídlo (nejčastěji oběd) kdy uvařila, aby se často neopakovala. Rozhodněte jak moc, na škále od 1 do 7, věta přiložená k seznamu významově odpovídá tomu, co Edita do seznamu zaznamenala.  </p><center> <p> <table><tr><th>Den</th><th>Jídlo</th></tr><tr><td>Pondělí</td><td>Guláš</td></tr><tr><td>Úterý</td><td>Lasagne</td></tr><tr><td>Středa</td><td>Koprovka</td></tr><tr><td>Čtvrtek</td><td>Špagety</td></tr><tr><td>Pátek</td><td>Rajská</td></tr><tr><td>Sobota</td><td>Segedýn</td></tr><tr><td>Neděle</td><td>Svíčková</td></tr></table> </p><p>Věta: <b> Edita na oběd vařívala jedno jídlo. </b></center></p>"}}],

[["first-item9-perf", 9], aj, {s: {html: "<p>Kreslířka Anna si zapisuje do seznamu, co kdy (nejčastěji po obědě) nakreslí. Rozhodněte jak moc, na škále od 1 do 7, věta přiložená k seznamu významově odpovídá tomu, co Anna do seznamu zaznamenala. </p><center> <p> <table><tr><th>Den</th><th>Objekt</th></tr><tr><td>Pondělí</td><td>Květinu</td></tr><tr><td>Úterý</td><td>Stůl</td></tr><tr><td>Středa</td><td>Strom</td></tr><tr><td>Čtvrtek</td><td>Vázu</td></tr><tr><td>Pátek</td><td>Kočku</td></tr><tr><td>Sobota</td><td>Dům</td></tr><tr><td>Neděle</td><td>List</td></tr></table> </p><p>Věta: <b> Anna každý den nakreslila jeden objekt. </b></center></p>"}}],
[["first-item9-hab", 9], aj, {s: {html: "<p>Kreslířka Anna si zapisuje do seznamu, co kdy (nejčastěji po obědě) nakreslí. Rozhodněte jak moc, na škále od 1 do 7, věta přiložená k seznamu významově odpovídá tomu, co Anna do seznamu zaznamenala. </p><center> <p> <table><tr><th>Den</th><th>Objekt</th></tr><tr><td>Pondělí</td><td>Květinu</td></tr><tr><td>Úterý</td><td>Stůl</td></tr><tr><td>Středa</td><td>Strom</td></tr><tr><td>Čtvrtek</td><td>Vázu</td></tr><tr><td>Pátek</td><td>Kočku</td></tr><tr><td>Sobota</td><td>Dům</td></tr><tr><td>Neděle</td><td>List</td></tr></table> </p><p>Věta: <b> Anna kreslívala jeden objekt. </b></center></p>"}}],
[["first-item9-gen", 9], aj, {s: {html: "<p>Kreslířka Anna si zapisuje do seznamu, co kdy (nejčastěji po obědě) nakreslí. Rozhodněte jak moc, na škále od 1 do 7, věta přiložená k seznamu významově odpovídá tomu, co Anna do seznamu zaznamenala. </p><center> <p> <table><tr><th>Den</th><th>Objekt</th></tr><tr><td>Pondělí</td><td>Květinu</td></tr><tr><td>Úterý</td><td>Stůl</td></tr><tr><td>Středa</td><td>Strom</td></tr><tr><td>Čtvrtek</td><td>Vázu</td></tr><tr><td>Pátek</td><td>Kočku</td></tr><tr><td>Sobota</td><td>Dům</td></tr><tr><td>Neděle</td><td>List</td></tr></table> </p><p>Věta: <b> Anna po obědě kreslívala jeden objekt.</b></center></p>"}}],



["firstfiller1-good", aj, {s: {html: "<p>Pět dětí ve třídě dostalo za úkol nakreslit jedno zvíře. Rozhodněte jak moc, na škále od 1 do 7, věta zapsaná panem učitelem a přiložená k seznamu významově odpovídá tomu, co popisuje tabulka.</p><center> <p> <table><tr><th>Dítě</th><th>Zvíře</th></tr><tr><td>Jan</td><td>prase</td></tr><tr><td>Marie</td><td>kůň</td></tr><tr><td>Petr</td><td>pes</td></tr><tr><td>Markéta</td><td>kráva</td></tr><tr><td>Jana</td><td>kočka</td></tr></table> </p><p>Věta: <b>Každé dítě nakreslilo jedno zvíře.</b></center></p>" }}],

["firstfiller2-bad", aj, {s: {html: "<p>Pět studentů dostalo v hodině za úkol vyjmenovat jednu zemi. Rozhodněte jak moc, na škále od 1 do 7, věta zapsaná panem učitelem a přiložená k seznamu významově odpovídá tomu, co popisuje tabulka.</p><center> <p> <table><tr><th>Student</th><th>Země</th></tr><tr><td>Jan</td><td>Francie</td></tr><tr><td>Marie</td><td>Německo</td></tr><tr><td>Petr</td><td>Itálie</td></tr><tr><td>Markéta</td><td>Španělsko</td></tr><tr><td>Jana</td><td>Česko</td></tr></table> </p><p>Věta: <b>Existuje jedna země, ktrou vyjmenoval každý student.</b></center></p>" }}],

["firstfiller3-good", aj, {s: {html: "<p>Pět policistů dostalo za úkol zatknout jednoho zločince. Rozhodněte jak moc, na škále od 1 do 7, věta zapsaná jejich nadřízeným a přiložená k seznamu významově odpovídá tomu, co popisuje tabulka.</p><center> <p> <table><tr><th>Policista</th><th>Zločinec</th></tr><tr><td>Petr</td><td>zloděj koní</td></tr><tr><td>Marie</td><td>vrah koček</td></tr><tr><td>Jan</td><td>sňatkový podvodník</td></tr><tr><td>Markéta</td><td>zloděj aut</td></tr><tr><td>Jana</td><td>pašerák drog</td></tr></table> </p><p>Věta: <b>Každý policista zatknul jednoho zločince.</b></center></p>" }}],

["firstfiller4-bad", aj, {s: {html: "<p>Pět malířů dostalo za úkol namalovat jedno město. Rozhodněte jak moc, na škále od 1 do 7, věta zapsaná jejich učitelem a přiložená k seznamu významově odpovídá tomu, co popisuje tabulka.</p><center> <p> <table><tr><th>Malíř</th><th>Město</th></tr><tr><td>Jan</td><td>Paříž</td></tr><tr><td>Marie</td><td>Berlín</td></tr><tr><td>Petr</td><td>Řím</td></tr><tr><td>Markéta</td><td>Madrid</td></tr><tr><td>Jana</td><td>Praha</td></tr></table> </p><p>Věta: <b>Existuje jedno město, které namaloval každý malíř.</b></center></p>" }}],

["firstfiller5-good", aj, {s: {html: "<p>Pět myslivců vyrazilo na lov a ulovilo zvířata, viz tabulka. Rozhodněte jak moc, na škále od 1 do 7, věta zapsaná jedním z nich významově odpovídá tomu, co popisuje tabulka.</p><center> <p> <table><tr><th>Myslivec</th><th>Zvíře</th></tr><tr><td>Petr</td><td>zajíc</td></tr><tr><td>Marie</td><td>srnec</td></tr><tr><td>Jan</td><td>jelen</td></tr><tr><td>Markéta</td><td>liška</td></tr><tr><td>Jana</td><td>prase</td></tr></table> </p><p>Věta: <b>Každý z myslivců ulovil po jednom zvířeti.</b></center></p>" }}],

["firstfiller6-bad", aj, {s: {html: "<p>Pět kuchařů připravovalo jídlo a použilo koření, viz tabulka. Rozhodněte jak moc, na škále od 1 do 7, věta zapsaná jedním z nich významově odpovídá tomu, co popisuje tabulka.</p><center> <p> <table><tr><th>Kuchař</th><th>Koření</th></tr><tr><td>Petr</td><td>kurkuma</td></tr><tr><td>Marie</td><td>pepř</td></tr><tr><td>Jan</td><td>kmín</td></tr><tr><td>Markéta</td><td>chilli</td></tr><tr><td>Jana</td><td>kardamom</td></tr></table> </p><p>Věta: <b>Existuje jedno koření, které použil každý kuchař.</b></center></p>" }}],

["firstfiller7-good", aj, {s: {html: "<p>Pět lékářů vyprávělo o nemocech svých pacientů. Rozhodněte jak moc, na škále od 1 do 7, věta zapsaná jedním z nich významově odpovídá tomu, co popisuje tabulka.</p><center> <p> <table><tr><th>Lékář</th><th>Nemoc</th></tr><tr><td>Petr</td><td>chřipka</td></tr><tr><td>Marie</td><td>zápal plic</td></tr><tr><td>Jan</td><td>angína</td></tr><tr><td>Markéta</td><td>zlomenina</td></tr><tr><td>Jana</td><td>slepé střevo</td></tr></table> </p><p>Věta: <b>Každý lékář vyprávěl o jedné nemoci.</b></center></p>" }}],

["firstfiller8-bad", aj, {s: {html: "<p>Pět zahradníků se staralo o zahrady a pěstovalo květiny, viz tabulka. Rozhodněte jak moc, na škále od 1 do 7, věta zapsaná jedním z nich významově odpovídá tomu, co popisuje tabulka.</p><center> <p> <table><tr><th>Jméno</th><th>Květina</th></tr><tr><td>Petr</td><td>růže</td></tr><tr><td>Marie</td><td>tulipány</td></tr><tr><td>Jan</td><td>lilie</td></tr><tr><td>Markéta</td><td>fialky</td></tr><tr><td>Jana</td><td>orchideje</td></tr></table> </p><p>Věta: <b>Existuje jedna květina, kterou pěstoval každý zahradník.</b></center></p>" }}],

["firstfiller9-good", aj, {s: {html: "<p>Pět cestovatelů vyrazilo na cestu a navštívilo země, viz tabulka. Rozhodněte jak moc, na škále od 1 do 7, věta zapsaná jedním z nich významově odpovídá tomu, co popisuje tabulka.</p><center> <p> <table><tr><th>Cestovatel</th><th>Země</th></tr><tr><td>Petr</td><td>Francie</td></tr><tr><td>Marie</td><td>Německo</td></tr><tr><td>Jan</td><td>Itálie</td></tr><tr><td>Markéta</td><td>Španělsko</td></tr><tr><td>Jana</td><td>Česko</td></tr></table></p><p>Věta: <b>Každý z cestovatelů navštívil jednu zemi.</b></center></p>" }}],

];
